config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :admins
  root to: "projects#index"
    
  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'
  
  resources :courses do
    member { put :mercury_update }
  end
  
  resources :admins

  resources :students

  resources :projects do 
    member { put :mercury_update }
  end

  resources :instructors
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>", :cropped => "200x200" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :courses_instructors, dependent: :destroy
	has_many :instructors, through: :courses_instructors

	has_many :courses_projects, dependent: :destroy
	has_many :projects, through: :courses_projects

	has_attached_file :image, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/courses_instructor.rb
class CoursesInstructor < ActiveRecord::Base
  belongs_to :course
  belongs_to :instructor
end

app/models/courses_project.rb
class CoursesProject < ActiveRecord::Base
  belongs_to :course
  belongs_to :project
end

app/models/instructor.rb
class Instructor < Admin
	has_many :courses_instructors, dependent: :destroy
	has_many :courses, through: :courses_instructors

	has_many :instructors_projects, dependent: :destroy
	has_many :projects, through: :instructors_projects
end

app/models/instructors_project.rb
class InstructorsProject < ActiveRecord::Base
  belongs_to :instructor
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :courses_projects, dependent: :destroy
	has_many :courses, through: :courses_projects

	has_many :projects_students, dependent: :destroy
	has_many :students, through: :projects_students

	has_many :instructors_projects, dependent: :destroy
	has_many :instructors, through: :instructors_projects

	has_attached_file :image, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  	# validates_attachment_presence :image, false
	#TUTAJ!!!!!!!!!!


end

app/models/projects_student.rb
class ProjectsStudent < ActiveRecord::Base
  belongs_to :project
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :projects_students, dependent: :destroy
	has_many :projects, through: :projects_students
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :set_admin, only: [:show, :update, :destroy]

	def index
    	@admins = Admin.all
  	end

	def show
	end

	def new
		redirect_to new_admin_registration_path
	end

	def edit
		redirect_to edit_admin_registration_path
	end

	def destroy
		@admin.destroy
		redirect_to admins_url
	end

	private
	def set_admin
      	@admin = Admin.find(params[:id])
	end
	
	def admin_params
	    params.require(:admin).permit(:name, :surname, :contact_email, :photo)
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :set_course, only: [:show, :edit, :destroy, :mercury_update, :update]
	before_action :authenticate_admin!, only: [:new, :create, :edit, :mercury_update, :destroy, :update]

	def index
    	@courses = Course.all
  	end

	def show
	end

	def update
		@course.image = course_params[:image]
		@course.save!
		# @course.update(course)
		redirect_to '/editor' + course_path
	end

	def new
		@course = Course.new
	end

	def create 
		@course = Course.new(course_params)
  		@course.save
  		redirect_to @course
	end

	def edit
		redirect_to '/editor' + course_path
	end

	def mercury_update
		@course.name = params[:content][:course_name][:value]
		@course.abbreviation = params[:content][:course_abbreviation][:value]
		@course.description = params[:content][:course_description][:value]
	  	@course.save!
	 	render text: ''
	end

	def destroy
		@course.destroy
		redirect_to courses_url
	end

	private
	def set_course
      	@course = Course.find(params[:id])
	end
	
	def course_params
	    params.require(:course).permit(:name, :abbreviation, :description, :image)
	end
end

app/controllers/mercury_controller.rb
class MercuryController < ActionController::Base
  #include ::Mercury::Authentication
  #before_filter :authenticate, :only => :edit
  before_filter :authenticate_admin!, only: [:edit]

  protect_from_forgery
  layout false

  def edit
    render :text => '', :layout => 'mercury'
  end

  def resource
    render :action => "/#{params[:type]}/#{params[:resource]}"
  end

  def snippet_options
    @options = params[:options] || {}
    render :action => "/snippets/#{params[:name]}/options"
  end

  def snippet_preview
    render :action => "/snippets/#{params[:name]}/preview"
  end

  def test_page
    render :text => params
  end

  private

  def authenticate
    redirect_to "/#{params[:requested_uri]}" unless can_edit?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:show, :destroy, :mercury_update, :update]


	def index
    	@projects = Project.all
  	end

	def show
		@instructors = @project.instructors.all
		@courses = @project.courses.all
	end

	def new
		@project = Project.new
	end

	def create 
		@project = Project.new(project_params)
  		@project.save
  		redirect_to @project
	end

	def update
		@project.image = project_params[:image]
		@project.save!

		redirect_to '/editor' + project_path
	end

	def mercury_update
		@project.title = params[:content][:project_title][:value]
		@project.description = params[:content][:project_description][:value]
		@project.author = params[:content][:project_author][:value]
		@project.author_email = params[:content][:project_author_email][:value]
	  	@project.save!
	 	render text: ''
	end

	def destroy
		@project.destroy
		redirect_to projects_url
	end

	private
	def set_project
      	@project = Project.find(params[:id])
	end
	
	def project_params
	    params.require(:project).permit(:title, :description, :image, :author, :author_email)
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :set_student, only: [:show, :edit, :update, :destroy]

	def index
    	@students = Student.all
  	end

	def show
	end

	def new
		@student = Student.new
	end

	def create 
		@student = Student.new(student_params)
  		@student.save
  		redirect_to @student
	end

	def edit
	end

	def update
		@student.update(student_params)
		redirect_to @student
	end

	def destroy
		@student.destroy
		redirect_to students_url
	end

	private
	def set_student
      	@student = Student.find(params[:id])
	end
	
	def student_params
	    params.require(:student).permit(:name, :surname, :student_number, :email, :website)
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admins/_form.html.erb
<%= form_for @admin do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

    <p>
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </p>

  <p>
    <%= f.label :contact_email %><br>
    <%= f.text_field :contact_email %>
  </p>
  <p>
      <%= f.label :photo, :class => 'control-label' %>
    
      <%= f.file_field :photo, :class => 'file_field' %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table>
  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.surname %></td>
        <td><%= admin.email %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %> |</td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New admin', new_admin_path %>
<%= link_to 'Sign out', destroy_admin_session_path, method: 'delete' %>

app/views/admins/new.html.erb
<h1>New admin</h1>
<%= render 'form' %>

app/views/admins/show.html.erb
  <%= @admin.name %>

  <%= @admin.surname %>

  <%= @admin.contact_email %>

  <%= image_tag @admin.photo.url(:thumb) %>

<%= link_to 'Edit', edit_admin_path %> |
<%= link_to 'Back', admin_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Portfolio" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  
  <body>

      <%= nav_bar :brand => "Portfolio", :brand_link => root_path, :fixed => :top, :responsive => true do  %>  
       
        <% menu_group do %>
          <%= menu_item "Courses", courses_path %>
          <%= menu_item "Instructors", instructors_path %>
          
          <%= menu_divider %>
         
         <% if current_admin %>
            <%= drop_down "Add" do %>
            <%= menu_item "Course", new_course_path %>
            <%= menu_item "Project", new_project_path %>
          <% end %>
            <% if controller.action_name == 'show' && controller.controller_name != 'instructors' %>
              <% if request.original_url.include?('mercury') %>
                <%= menu_item "Stop editing #{controller.controller_name[0..-2]}", request.path%>
              <% else %>
                <%= menu_item "Edit #{controller.controller_name[0..-2]}", '/editor' + request.path%>
              <% end %>
            <% end %>
            <%= menu_item "My Account", edit_admin_registration_path %>
            <%= menu_item "Log Out", destroy_admin_session_path, method: 'delete' %>
         <% else %>
            <%= menu_item "Sign In", new_admin_session_path %>
         <% end %>
       <% end %>  
      <% end %>
  
      <div class="container">

          <%= yield %>
      </div>


  <!--     <footer>
        <p>&copy; Company 2014</p>
      </footer> -->

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  null, // 'form', or 'json' (default json)
        saveMethod: null, // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>