config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :admins
  root to: "projects#index"
    
  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'
  
  resources :courses do
    member { put :mercury_update }
  end
  
  resources :admins

  resources :students

  resources :projects do 
    member { put :mercury_update }
  end

  resources :instructors
  

end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :projects_students, dependent: :destroy
	has_many :projects, through: :projects_students
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :set_student, only: [:show, :edit, :update, :destroy]

	def index
    	@students = Student.all
  	end

	def show
	end

	def new
		@student = Student.new
	end

	def create 
		@student = Student.new(student_params)
  		@student.save
  		redirect_to @student
	end

	def edit
	end

	def update
		@student.update(student_params)
		redirect_to @student
	end

	def destroy
		@student.destroy
		redirect_to students_url
	end

	private
	def set_student
      	@student = Student.find(params[:id])
	end
	
	def student_params
	    params.require(:student).permit(:name, :surname, :student_number, :email, :website)
	end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

    <p>
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </p>

  <p>
    <%= f.label :student_number %><br>
    <%= f.text_field :student_number %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/students/edit.html.erb
<h1>Edit admins</h1>

<%= render 'form' %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.surname %></td>
        <td><%= student.student_number %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %> |</td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New student', new_student_path %>

app/views/students/new.html.erb
<h1>New admin</h1>
<%= render 'form' %>

app/views/students/show.html.erb
  <%= @student.name %>

  <%= @student.surname %>

  <%= @student.student_number %>

  <%= @student.email %>

  <%= @student.website %>

<%= link_to 'Edit', edit_student_path %> |
<%= link_to 'Back', student_path %>